// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {BaseClientOptions} from "@xata.io/client";


export type DatabaseSchema = {};

const DatabaseClient = buildClient();


const defaultOptions = {
  databaseURL:
      "https://Bumba-jr-s-workspace-r3dfm3.eu-central-1.xata.sh/db/jsm_Snapcast",
  apiKey: process.env.XATA_API_KEY, // ✅ correct key name
  branch: "main",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
